version: "3.7"

services:
  node:
    build:
      context: ./node
      dockerfile: Dockerfile
    image: arialdomartini/private-ethereum
    container_name: ethereum-node
    entrypoint: /app/start.sh
    volumes:
      - type: volume
        source: ipc
        target: /app/ipc

  console:
    build:
      context: ./console
      dockerfile: Dockerfile
    image: arialdomartini/private-ethereum-console
    container_name: ethereum-console
    volumes:
      - type: volume
        source: ipc
        target: /app/ipc

  compiler:
    build:
      context: ./compiler
      dockerfile: Dockerfile
    image: arialdomartini/private-ethereum-solc
    container_name: ethereum-solc
    volumes:
      - .:/src

volumes:
  ipc:
